# Generated by Django 5.0.3 on 2024-03-31 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_category_clothingclass_clothingitem_delete_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='clothing_class',
            new_name='classname',
        ),
    ]
