# Generated by Django 5.0.3 on 2024-03-31 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_clothing_class_clothingitem_classname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='classname',
            new_name='clothing_class',
        ),
    ]
