# Generated by Django 5.0.3 on 2024-04-03 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_classname_clothingitem_clothing_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='clothing_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.clothingclass'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='clothing_images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.CharField(default='default_text', max_length=200),
        ),
    ]
